# $FreeBSD$

PORTNAME=	libcez
PORTVERSION=	1.0
CATEGORIES=	devel

MAINTAINER=	koue@chaosophia.net
COMMENT=	Collection of useful functions

LICENSE=	BSD2CLAUSE

LIB_DEPENDS=	libsqlite3.so:databases/sqlite3

USE_GITHUB=	yes
GH_ACCOUNT=	koue
GH_PROJECT=	libcez

MYSQL_USES=	mysql

CFLAGS+=	-Wall

MAKE_ARGS+=	BINDIR=${PREFIX}/sbin MANDIR=${PREFIX}/man/man

PLIST_FILES=	include/cez.h \
		include/cson_amalgamation.h \
		lib/libcez.a

.include <bsd.port.mk>
