#
MK_PROFILE=	no
LOCALBASE?=	/usr/local
LIB=		ceznethttp
LIBDIR=		${LOCALBASE}/lib
INCSDIR=	${LOCALBASE}/include
CFLAGS+=	-Wall -Wstrict-prototypes -fPIC -I${.CURDIR} -I${.CURDIR}/../core
SRCS=		http.c cez_net_http.h
INCS=		cez_net_http.h
NO_OBJ=		yes

.include <bsd.lib.mk>
