#
MK_PROFILE=	no
LOCALBASE?=	/usr/local
LIB=		cezutil
LIBDIR=		${LOCALBASE}/lib
INCSDIR=	${LOCALBASE}/include
CFLAGS+=	-Wall -Wstrict-prototypes -I${.CURDIR}
SRCS=		cez_util.h util.c
INCS=		cez_util.h
NO_OBJ=		yes

.include <bsd.lib.mk>
