#
T_FILES=	footer.t \
		header.t \
		status.t \
		tb_icon.t \
		toolbar.t \
		toolbar_left.t \
		toolbar_right.t \
		welcome.t \
		welcome_help.t

HTML=		welcome.html

include ../share/mk/templates.mk
include Makefile.deps
