#
LIB=            cezconfig
CFLAGS+=        -Wall -Wstrict-prototypes -I${.CURDIR}
SRCS=           configfile.c config-array.c config-queue.c cez-config.h
INCS=           cez-config.h
NO_OBJ=         yes

.include <bsd.lib.mk>
