#
MK_PROFILE=	no
LOCALBASE?=	/usr/local
LIB=            cezcorelist
LIBDIR=		${LOCALBASE}/lib
INCSDIR=	${LOCALBASE}/include
CFLAGS+=        -Wall -Wstrict-prototypes -fPIC -I${.CURDIR}
SRCS=		list.c \
		cez_core_list.h

INCS=		cez_core_list.h

NO_OBJ=         yes

.include <bsd.lib.mk>
